### ISSUE TITLE
pytest 7 support

### ISSUE THREAD

**Issue by last-partizan** [theY4Kman/pytest-common-subject#2]
Hi, is this project alive and well?

I'm using `pytest-drf` and would like to update to pytest-7 but this and `pytest-lambda` are blocking update.

Do you have any plans for updating? need help?

**Comment by theY4Kman** [comment]
Whoops, that's my bad. I guess I've gotta step up my alerting game on new pytest major versions.

I pushed out a new `pytest-lambda` release with pytest 7.x "support"; I'm handling the others now.

I'm pretty good with pull requests, if you want stuff even quicker. All the projects have tests, and I think most of them have tox configs now. But it's no problem for me to take care of them — just FYI.

Also, thank you for opening the issue :) And after seeing that pytest 7.x got released _months_ ago, I think I owe an apology :P

**Comment by last-partizan** [comment]
Great news, thank you!

**Comment by theY4Kman** [comment]
Okie dokes, with [pytest-lambda 1.2.6](https://pypi.org/project/pytest-lambda/1.2.6/) and [pytest-common-subject 1.0.6](https://pypi.org/project/pytest-common-subject/1.0.6/), pytest-drf can now be installed alongside 7.x. pytest-drf itself doesn't have any upper limit to its version pinning, so it didn't actually need any changes, but I added tox tests for all supported versions, just for good measure (and to tax my machine... there are now 80 tox envs >_> ).

One of these days, I'm sure I'll just break down and remove the upper limits on the pytest plugins, and just respond to bug reports if there are incompatibilities. But a large part of me still feels a level of solidity knowing that if the package can be installed, it will work — and so I keep the upper limits. On the other hand, it _does_ require me to stay on top of things, and I know what it feels like to be the one held back from upgrading _other_ deps due to some stupid library holding things back (e.g. right now, I can't upgrade to Python 3.10, because spaCy doesn't support pydantic 1.9.x, and pydantic 1.8.x doesn't support Python 3.10), so I might break down next major pytest release :P

(On that rant: I don't know if you've ever worked with Gradle in Java-land, but it has the ability to override/substitute dependencies, which is just _shockingly_ absent from the Python world. Like, what the hell? I actually only use _one_ single feature of spaCy, which works JUST FINE with pydantic 1.9, and yet I can't install it IN MY OWN ENVIRONMENT because some other open-source developer — who has their own life — hasn't gotten to it, yet. It's fuckin nanners!)

Anyway, thanks for giving me the heads-up, and holler if you run into any other issues <3

**Comment by last-partizan** [comment]
Thanks for quick update!

https://github.com/theY4Kman/pytest-fixture-order/issues/2#issuecomment-1127184001

One last part of the puzzle, and we will be able to use pytest-drf with pytest-7 :)

Thanks for quick update!

(I didn't work with Java or Gradle, but hell, that looks useful. Probably, python ecosystem doesn't have anything like it becouse we can complain about version incompatibility and it will be fixed next day :) )
